### ISSUE TITLE
wish to see your source code soon

### ISSUE THREAD

**Issue by lafiteee** [VITA-Group/CADTransformer#1]
I'm a postgraduate student of Fudan University in China. I've read your article CADTransformer, and I'm so intrested in your research. Looking forward to your source code.

**Comment by zhiwenfan** [comment]
Thanks for your interest, we will start releasing the relevant code before the CVPR conference. 
As the dataset of FloorPlanCAD has updated, we need to re-organize all previous code to fit the current data format.
Thanks again for your understanding!
