### ISSUE TITLE
Incomplete code

### ISSUE THREAD

**Issue by MarkMoHR** [VITA-Group/CADTransformer#2]
Hi, thank you for releasing the code!
But I couldn't find the script `train_cad_ddp.py`. Would it be possible to release it along with your trained models?

**Comment by zhiwenfan** [comment]
Hi, we are completing the evaluation code based on floorplanCAD v2, the code will release in the next few weeks. Thanks.

**Comment by lpasselin** [comment]
@zhiwenfan Is there any progress on this? Your paper says the code is available.
