### ISSUE TITLE
Dataset download links do not work

### ISSUE THREAD

**Issue by olbod** [VITA-Group/CADTransformer#4]
I have tried to download the dataset on the official website here https://floorplancad.github.io/. It seems the data doesn't exist anymore.

**Comment by zhiwenfan** [comment]
try: python preprocess/download_data.py  --data_save_dir  /ssd1/zhiwen/datasets/svg_raw

**Comment by ogencoglu** [comment]
What is the relationship between image patches? Are they tiled versions of a larger image? Are file names some sort of coordinates? Is there overlap?

Anyone figured that out?
