### ISSUE TITLE
What version of timm do your code use?

### ISSUE THREAD

**Issue by youngmac1106** [VITA-Group/CADTransformer#6]
Thanks for your awesome work.

As I run the code 
`CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 train_cad_ddp.py --data_root /PATH/TO/PROJECT_DIR/data/FloorPlanCAD --pretrained_model /PATH/TO/PROJECT_DIR/pretrained_models/hrnetv2_w48_imagenet_pretrained.pth`
some errors occured.

```
Traceback (most recent call last):
  File "train_cad_ddp.py", line 8, in <module>
    from models.model import CADTransformer
  File "/studio/CADTransformer-main/models/model.py", line 19, in <module>
    from vit import get_vit
  File "/studio/CADTransformer-main/models/vit.py", line 10, in <module>
    from timm.models.vision_transformer import VisionTransformer, _create_vision_transformer, _init_vit_weights, checkpoint_filter_fn, default_cfgs
ImportError: cannot import name '_init_vit_weights' from 'timm.models.vision_transformer' (/opt/conda/envs/cad/lib/python3.7/site-packages/timm/models/vision_transformer.py)


```

I can't find `_init_vit_weights` in the latest [`timm`](https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/vision_transformer.py) either. The latest version is 0.6.11

Look forward to your reply.

**Comment by zhiwenfan** [comment]
>>> timm.__version__
'0.4.12'
